replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - /
  annotations:
    kubernetes.io/ingress.class: nginx

application:
  logs:
    ignore:
      ping: true
